name: Build go app and push to Azure

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./cmd/main

#     - name: Test
#       run: go test -v ./tests

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: cwq2326
        package: build/
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
